import React from 'react';
import { tradeOpportunities } from '@/data/mockData';
import { TradingCard } from '@/components/ui/card';
import { TrendingUp, TrendingDown, Minus, Brain, AlertTriangle } from 'lucide-react';

const Opportunities: React.FC = () => {
  const getDirectionIcon = (direction: string) => {
    switch (direction) {
      case 'Long':
        return <TrendingUp className="w-5 h-5 text-success" />;
      case 'Short':
        return <TrendingDown className="w-5 h-5 text-destructive" />;
      default:
        return <Minus className="w-5 h-5 text-muted-foreground" />;
    }
  };

  const getConditionBadge = (condition: string) => {
    switch (condition) {
      case 'Trending':
        return 'badge-success';
      case 'Ranging':
        return 'badge-warning';
      default:
        return 'badge-muted';
    }
  };

  const getValidityBadge = (validity: string) => {
    switch (validity) {
      case 'Valid':
        return 'badge-success';
      case 'Almost':
        return 'badge-warning';
      default:
        return 'badge-destructive';
    }
  };

  const getConfidenceColor = (confidence: number) => {
    if (confidence >= 70) return 'text-success';
    if (confidence >= 50) return 'text-warning';
    return 'text-destructive';
  };

  return (
    <div className="min-h-screen p-6 lg:p-8">
      <div className="mb-8">
        <div className="flex items-center gap-3 mb-2">
          <Brain className="w-8 h-8 text-primary" />
          <h1 className="text-2xl font-bold text-foreground">Trade Opportunities</h1>
        </div>
        <p className="text-muted-foreground">AI-powered analysis of potential trades based on System 1 rules</p>
      </div>

      {/* Disclaimer */}
      <div className="glass-card p-4 mb-6 border-warning/30 bg-warning/5">
        <div className="flex items-start gap-3">
          <AlertTriangle className="w-5 h-5 text-warning shrink-0 mt-0.5" />
          <div>
            <p className="text-sm text-warning font-medium">AI Analysis Disclaimer</p>
            <p className="text-xs text-muted-foreground mt-1">
              These opportunities are generated by mock AI analysis for demonstration purposes. 
              Always perform your own analysis before entering any trade.
            </p>
          </div>
        </div>
      </div>

      {/* Opportunities Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {tradeOpportunities.map((opp) => (
          <TradingCard key={opp.pair} className="cursor-default">
            {/* Header */}
            <div className="flex items-center justify-between mb-4">
              <div className="flex items-center gap-3">
                {getDirectionIcon(opp.direction)}
                <div>
                  <h3 className="font-semibold text-lg text-foreground">{opp.pair}</h3>
                  <p className="text-sm font-mono text-muted-foreground">{opp.price.toFixed(opp.pair.includes('JPY') ? 2 : 4)}</p>
                </div>
              </div>
              <div className="text-right">
                <p className="text-sm text-muted-foreground mb-1">AI Confidence</p>
                <p className={`text-2xl font-bold font-mono ${getConfidenceColor(opp.confidence)}`}>
                  {opp.confidence}%
                </p>
              </div>
            </div>

            {/* Status Badges */}
            <div className="flex flex-wrap gap-2 mb-4">
              <span className={getConditionBadge(opp.condition)}>{opp.condition}</span>
              <span className={getValidityBadge(opp.validity)}>{opp.validity}</span>
              {opp.direction !== 'None' && opp.direction !== 'Neutral' && (
                <span className={opp.direction === 'Long' ? 'badge-success' : 'badge-destructive'}>
                  {opp.direction}
                </span>
              )}
            </div>

            {/* Confidence Bar */}
            <div className="mb-4">
              <div className="h-2 bg-secondary rounded-full overflow-hidden">
                <div 
                  className={`h-full rounded-full transition-all duration-500 ${
                    opp.confidence >= 70 ? 'bg-success' : opp.confidence >= 50 ? 'bg-warning' : 'bg-destructive'
                  }`}
                  style={{ width: `${opp.confidence}%` }}
                />
              </div>
            </div>

            {/* AI Explanation */}
            <div className="bg-secondary/30 rounded-lg p-4">
              <div className="flex items-center gap-2 mb-2">
                <Brain className="w-4 h-4 text-primary" />
                <span className="text-sm font-medium text-foreground">AI Analysis</span>
              </div>
              <p className="text-sm text-muted-foreground leading-relaxed">
                {opp.explanation}
              </p>
            </div>
          </TradingCard>
        ))}
      </div>

      {/* Summary Stats */}
      <div className="mt-8 glass-card p-6">
        <h2 className="text-lg font-semibold text-foreground mb-4">Analysis Summary</h2>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div>
            <p className="text-sm text-muted-foreground">Valid Setups</p>
            <p className="text-2xl font-bold font-mono text-success">
              {tradeOpportunities.filter(o => o.validity === 'Valid').length}
            </p>
          </div>
          <div>
            <p className="text-sm text-muted-foreground">Almost Ready</p>
            <p className="text-2xl font-bold font-mono text-warning">
              {tradeOpportunities.filter(o => o.validity === 'Almost').length}
            </p>
          </div>
          <div>
            <p className="text-sm text-muted-foreground">Avg Confidence</p>
            <p className="text-2xl font-bold font-mono text-foreground">
              {Math.round(tradeOpportunities.reduce((acc, o) => acc + o.confidence, 0) / tradeOpportunities.length)}%
            </p>
          </div>
          <div>
            <p className="text-sm text-muted-foreground">Trending Pairs</p>
            <p className="text-2xl font-bold font-mono text-foreground">
              {tradeOpportunities.filter(o => o.condition === 'Trending').length}
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Opportunities;
